### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by Lesco404** [DizzasTeR/Vultaic-MGM#4]
How can i get avatars to work?

**Comment by rasikhq** [comment]
You have to setup the MTA web SDK to send a remote request and then depending on the forum scripts that you use (SMF, IPS, etc) you return the absolute avatar URL which v_avatar can process

**Comment by Lesco404** [comment]
But its not working i need a cachedavatars folder but where do i need to put it?

**Comment by rasikhq** [comment]
the avatarcache folder will be  auto generated in v_avatars

You need to setup a web server alias called "mainavatarcache" that points to the v_avatars/avatarcache directory and then they will start working
