### ISSUE TITLE
Help Mirage Or Dizzaster Please 

### ISSUE THREAD

**Issue by Ashrafkaddour19** [DizzasTeR/Vultaic-MGM#5]
Bro i have problem I fixed everything but when I go into HDM or Shooter or Derby it says Couldn't Find Map please reply urgently
![mta-screen_2022-10-14_21-20-59](https://user-images.githubusercontent.com/115896070/196003037-ca31151d-3c2d-4ba3-ae0e-ba6f1a3c8674.png)

**Comment by Ashrafkaddour19** [comment]
![Uploading mta-screen_2022-10-14_21-21-06.png…]()

**Comment by rasikhq** [comment]
You probably don't have the maps that get detected for these arenas
