### ISSUE TITLE
Map loads but does not start

### ISSUE THREAD

**Issue by Cveramz** [DizzasTeR/Vultaic-MGM#7]
Hello, I solved some issues that were preventing me from starting everything, but when trying to enter an arena, it doesn't start. The map loads correctly but doesn't start. Could it be missing a script or gamemode? I attach an image.
![image](https://github.com/DizzasTeR/Vultaic-MGM/assets/83312809/99221b87-a6c7-437c-b141-739f66c52530)

**Comment by rasikhq** [comment]
Check your debugscript logs for any errors, also I am no longer providing free support for this project
